# Copyright (c) 2023-2025 tinyVision.ai Inc.
# SPDX-License-Identifier: MIT

manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.2.0
      import:
        name-allowlist:
          - zephyr
