# Copyright (c) 2023-2024 tinyVision.ai Inc.
# SPDX-License-Identifier: MIT

manifest:
  projects:

    - name: zephyr
      url: git@github.com:tinyvision-ai-inc/zephyr
      revision: pr-usb3-uvc
      import:
        name-allowlist:
          - zephyr
